"""add description to projects

Revision ID: 1275f0aa6432
Revises: 3ad15c67ae23
Create Date: 2025-12-12 19:12:39.145832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1275f0aa6432'
down_revision: Union[str, None] = '3ad15c67ae23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('fk_events_task_id_tasks', 'events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_events_task_id_tasks'), 'events', 'tasks', ['task_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('integrations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('fk_integrations_project_id_projects', 'integrations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_integrations_project_id_projects'), 'integrations', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('projects', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_constraint('fk_projects_owner_id_users', 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_owner_id_users'), 'projects', 'users', ['owner_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('tasks', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('fk_tasks_project_id_projects', 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_project_id_projects'), 'tasks', 'projects', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_tasks_created_by_users'), 'tasks', 'users', ['created_by'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_created_by_users'), 'tasks', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_project_id_projects'), 'tasks', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_tasks_project_id_projects', 'tasks', 'projects', ['project_id'], ['id'])
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('tasks', 'created_by')
    op.drop_constraint(op.f('fk_projects_owner_id_users'), 'projects', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_projects_owner_id_users', 'projects', 'users', ['owner_id'], ['id'])
    op.drop_column('projects', 'description')
    op.drop_constraint(op.f('fk_integrations_project_id_projects'), 'integrations', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_integrations_project_id_projects', 'integrations', 'projects', ['project_id'], ['id'])
    op.alter_column('integrations', 'created_at',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_events_task_id_tasks'), 'events', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_events_task_id_tasks', 'events', 'tasks', ['task_id'], ['id'])
    op.alter_column('events', 'created_at',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
